import numpy as np
from obspy.geodetics import gps2dist_azimuth, locations2degrees

from seispy.distaz import _geocentric_latitude, distaz


def test_matches_matlab_reference_values():
    # Expected values were generated by the supplied distaz.m. In that
    # routine, dazs maps to seispy's az and daze maps to seispy's baz.
    cases = [
        (
            (30.0, 100.0, -20.0, -70.0),
            (166.54292609894395, 40.338004084927235, 315.4341245865688),
        ),
        (
            (34.5, -117.2, -12.3, 145.6),
            (102.73866704064234, 57.14754691095879, 263.77588974047626),
        ),
        (
            (45.0, 170.0, 60.0, -170.0),
            (19.211952048737878, 227.5125712173198, 31.488076464108467),
        ),
        (
            (-35.0, 20.0, 70.0, 130.0),
            (129.25152060504627, 274.9776837339075, 24.67787010851666),
        ),
    ]

    for coordinates, expected in cases:
        result = distaz(*coordinates)
        np.testing.assert_allclose(
            (result.delta, result.az, result.baz),
            expected,
            rtol=0.0,
            atol=1.0e-12,
        )


def test_azimuth_convention_and_accessors_are_preserved():
    result = distaz(0.0, 0.0, 0.0, 90.0)

    assert result.getDelta() == 90.0
    assert result.getAz() == 270.0
    assert result.getBaz() == 90.0
    assert result.degreesToKilometers() == 90.0 * 111.19


def test_multidimensional_arrays_match_elementwise_scalar_results():
    lat1 = np.array([[12.0, -45.0, 70.0], [33.0, -10.0, 5.0]])
    lon1 = np.array([[10.0, 140.0, -120.0], [-75.0, 20.0, 179.0]])
    lat2 = np.array([[-30.0, 60.0, -20.0], [5.0, 45.0, -65.0]])
    lon2 = np.array([[130.0, -100.0, 20.0], [80.0, -160.0, -30.0]])

    vector_result = distaz(lat1, lon1, lat2, lon2)

    assert vector_result.delta.shape == lat1.shape
    for index in np.ndindex(lat1.shape):
        scalar_result = distaz(
            lat1[index],
            lon1[index],
            lat2[index],
            lon2[index],
        )
        np.testing.assert_allclose(
            (
                vector_result.delta[index],
                vector_result.az[index],
                vector_result.baz[index],
            ),
            (scalar_result.delta, scalar_result.az, scalar_result.baz),
            rtol=0.0,
            atol=1.0e-12,
        )

    assert np.all((vector_result.az >= 0.0) & (vector_result.az < 360.0))
    assert np.all((vector_result.baz >= 0.0) & (vector_result.baz < 360.0))


def test_all_coordinate_inputs_follow_numpy_broadcasting():
    result = distaz(
        np.array([[0.0], [30.0]]),
        10.0,
        np.array([[-20.0, 0.0, 40.0]]),
        np.array([20.0, 100.0, -150.0]),
    )

    assert result.delta.shape == (2, 3)
    assert result.az.shape == (2, 3)
    assert result.baz.shape == (2, 3)


def test_coincident_points_and_poles_return_zero():
    result = distaz(
        [0.0, 90.0, -90.0, 10.0],
        [0.0, 12.0, -48.0, 20.0],
        [0.0, 90.0, -90.0, 10.0],
        [360.0, 150.0, 72.0, 20.0],
    )

    np.testing.assert_array_equal(result.delta, np.zeros(4))
    np.testing.assert_array_equal(result.az, np.zeros(4))
    np.testing.assert_array_equal(result.baz, np.zeros(4))


def test_distance_matches_obspy_for_the_same_spherical_model():
    lat1 = np.array([[30.0], [34.5], [-35.0]])
    lon1 = np.array([[100.0], [-117.2], [20.0]])
    lat2 = np.array([[-20.0, -12.3, 70.0]])
    lon2 = np.array([[-70.0, 145.6, 130.0]])

    result = distaz(lat1, lon1, lat2, lon2)
    geocentric_lat1 = np.rad2deg(_geocentric_latitude(lat1))
    geocentric_lat2 = np.rad2deg(_geocentric_latitude(lat2))
    obspy_delta = locations2degrees(
        geocentric_lat1,
        lon1,
        geocentric_lat2,
        lon2,
    )

    np.testing.assert_allclose(
        result.delta,
        obspy_delta,
        rtol=0.0,
        atol=1.0e-12,
    )


def test_azimuths_match_obspy_for_the_same_spherical_model():
    earth_radius_m = 6_371_000.0
    cases = [
        (30.0, 100.0, -20.0, -70.0),
        (34.5, -117.2, -12.3, 145.6),
        (45.0, 170.0, 60.0, -170.0),
        (-35.0, 20.0, 70.0, 130.0),
    ]

    for lat1, lon1, lat2, lon2 in cases:
        result = distaz(lat1, lon1, lat2, lon2)
        geocentric_lat1 = np.rad2deg(_geocentric_latitude(lat1))
        geocentric_lat2 = np.rad2deg(_geocentric_latitude(lat2))
        distance_m, forward_azimuth, backward_azimuth = gps2dist_azimuth(
            geocentric_lat1,
            lon1,
            geocentric_lat2,
            lon2,
            a=earth_radius_m,
            f=0.0,
        )
        obspy_delta = np.rad2deg(distance_m / earth_radius_m)

        np.testing.assert_allclose(
            (result.delta, result.baz, result.az),
            (obspy_delta, forward_azimuth, backward_azimuth),
            rtol=0.0,
            atol=1.0e-10,
        )
