name: docs-post
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - pip
  - sphinx=4.5.0
  - sphinx-copybutton
  - sphinx-design
  - myst-nb
  - obspy=1.3.0
  - seispy
  - numpydoc
  - pip:
    - sphinx-gallery
    - sphinx-cjkspace
    - pydata-sphinx-theme
    - sphinx-panels
    - sphinx-icon