name: seispy-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pip
  - sphinx
  - sphinx-copybutton
  - sphinx-design
  - myst-nb
  - furo
  - obspy
  - numpydoc
  - pip:
    - sphinx-gallery
    - sphinx-cjkspace
    - sphinx-icon